USE [VEMAYBAY]
GO
/****** Object:  Table [dbo].[TICKET]    Script Date: 13/10/2021 23:36:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TICKET](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SOLD] [bit] NOT NULL,
	[BLOCK] [bit] NOT NULL,
 CONSTRAINT [PK_TICKET] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[TICKET] ON 
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (1, 1, 1)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (2, 1, 1)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (3, 1, 1)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (4, 0, 0)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (5, 1, 1)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (6, 1, 1)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (7, 1, 1)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (8, 1, 1)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (9, 0, 0)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (10, 1, 1)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (11, 1, 1)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (12, 0, 0)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (13, 0, 0)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (14, 0, 0)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (16, 0, 0)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (17, 0, 0)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (18, 0, 0)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (19, 0, 0)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (21, 1, 1)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (22, 1, 1)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (23, 1, 1)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (24, 0, 0)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (25, 0, 0)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (26, 1, 1)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (27, 1, 1)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (28, 0, 0)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (29, 0, 0)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (30, 1, 1)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (31, 1, 1)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (32, 0, 0)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (33, 0, 0)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (34, 0, 0)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (35, 0, 0)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (36, 1, 0)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (37, 1, 1)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (38, 1, 1)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (39, 0, 0)
GO
INSERT [dbo].[TICKET] ([ID], [SOLD], [BLOCK]) VALUES (40, 1, 1)
GO
SET IDENTITY_INSERT [dbo].[TICKET] OFF
GO
USE [master]
GO
ALTER DATABASE [VEMAYBAY] SET  READ_WRITE 
GO
